# 🧊 Glass Effect
background_opacity 0.85
background_blur 57

# 🎨 Font
font_family MesloLGS Nerd Font
font_size 13.0

# 🧼 Clean UI
window_padding_width 12
enable_audio_bell no

# ⚡ Cursor
cursor_shape block
cursor_blink_interval 0.5

# 🌈 Colors (soft anime vibe)
foreground #f8f8f2
background #1e1e2e

# Selection
selection_background #44475a
selection_foreground #ffffff

# title bar
linux_display_server x11
